version: "2"

services:
  app:
    image: golang:alpine
    volumes:
      - .:/go/src/fanatics
    working_dir: /go/src/fanatics
    command: go run main.go
    links:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis:6379


  redis:
    image: redis:alpine
    command: ["--notify-keyspace-events", "Kgx"]